### ISSUE TITLE
Specify content-type on responses

### ISSUE THREAD

**Issue by oliverjam** [fac-23/app-week1-team1#36]
https://github.com/fac-23/app-week1-team1/blob/b9a705f47fc04f3fd5525900f3dd5a62a3ea6d4f/server.js#L72

Your main HTML response does not have a content-type header. Most browsers assume the page is HTML and render it correctly, but they don't have to. It's possible some older browsers might render the page as raw text (e.g. you'd just see the underlying HTML source code).

The reason for the missing header is that you're using the default `response.end` method from Node. This doesn't do anything fancy—it just sends the response. If you use Express' special helper `response.send` (note the *s*!) then it'll automatically set the right content-type etc for you.

**Comment by NaincyKumariKnoldus** [comment]
Hello @oliverjam Can I do this please?

**Comment by NaincyKumariKnoldus** [comment]
Hey @paologhidoni Can you please tell me if you had merged my PR or not?
